addec ontact us section
KristinaRud/fe-10-101-final-project-1 pull request #40
Opened 2023-06-02 22:05 UTC by eteriasdragon

2023-06-05 19:38 UTC, KristinaRud commented on client/src/components/Header/Header.js
> +// import Item from "@mui/material/Item";
все лишние коментарии нужно убирать

2023-06-05 19:38 UTC, KristinaRud commented on client/src/components/Header/Item/Item.module.scss
> +}
добавь в конец файла энтер

2023-06-05 19:38 UTC, KristinaRud commented on client/src/components/Sliders/NewsSlider/NewsSlider.module.scss
>  }
добавь в конец файла энтер на 18строку

2023-06-05 19:38 UTC, KristinaRud commented on client/src/pages/ContactUs/ContactUs.helpers-config.js
> +};
добавь в конец файла энтер

2023-06-05 20:15 UTC, maksimsuheckiy requested changes

2023-06-05 20:15 UTC, maksimsuheckiy commented on client/src/components/Header/Item/Item.jsx
> +        <MenuItem className={styles.item} onClick={handleClose}>
тоже лучше через конфиг, поскольку Item-ы могут добавлятся в теории

2023-06-05 20:15 UTC, maksimsuheckiy commented on client/src/pages/ContactUs/ContactUs.jsx
>      console.log(values);
console.log не должен попадать в продакшн

2023-06-06 18:10 UTC, maksimsuheckiy commented
@eteriasdragon конфликты появились также

2023-06-17 18:53 UTC, closed without merging